// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code

using Blackbaud.UAT.SpecFlow.Selenium;
using TechTalk.SpecFlow;

#pragma warning disable

namespace BlackbaudDemo40.CRMFeatures
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Membership Programs")]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class MembershipProgramsFeature : BaseTest
    {
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        public Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext { get; set; } //;

        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            var featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"),
                "Membership Programs",
                "In order to manage Membership programs\r\nAs a BBCRM User\r\nI want to create a new M" +
                "embership Program", ProgrammingLanguage.CSharp, ((string[]) (null)));
            testRunner.OnFeatureStart(featureInfo);
        }

        [NUnit.Framework.TestFixtureTearDownAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        [NUnit.Framework.SetUpAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null)
                 && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Membership Programs")))
            {
                FeatureSetup(null);
            }
        }

        [NUnit.Framework.TearDownAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
            SaveChromeArtifacts(IsPass());
            StopDriver();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            ScenarioContext.Current.Add("Test", this);
            StartDriver();
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        public virtual bool IsPass()
        {
            var pass = false;
            try
            {
                pass = (NUnit.Framework.TestContext.CurrentContext.Result.Status == NUnit.Framework.TestStatus.Passed);
            }
            catch
            {
                pass = (TestContext.CurrentTestOutcome ==
                        Microsoft.VisualStudio.TestTools.UnitTesting.UnitTestOutcome.Passed);
            }
            return pass;
        }

        [NUnit.Framework.TestFixtureSetUpAttribute()]
        protected virtual void FeatureSetup()
        {
            FeatureSetup(null);
        }

        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a new Membership Program")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Create a new Membership Program")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Membership Programs")]
        public virtual void CreateANewMembershipProgram()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a new Membership Program", ((string[]) (null)));
#line 6
            this.ScenarioSetup(scenarioInfo);
#line 7
            testRunner.Given("I have logged into the BBCRM home page", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "Given ");
#line 8
            testRunner.And("there is no existing Membership Program called \"Test Program\"", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "And ");
#line hidden
            var table1 = new TechTalk.SpecFlow.Table(new string[]
            {
                "field",
                "value"
            });
            table1.AddRow(new string[]
            {
                "Name",
                "Test Program"
            });
            table1.AddRow(new string[]
            {
                "Kind",
                "Annual"
            });
            table1.AddRow(new string[]
            {
                "Obtain",
                "Dues"
            });
#line 9
            testRunner.When("I create a new membership with General options", ((string) (null)), table1, "When ");
#line hidden
            var table2 = new TechTalk.SpecFlow.Table(new string[]
            {
                "field",
                "value"
            });
            table2.AddRow(new string[]
            {
                "Name",
                "Level1"
            });
            table2.AddRow(new string[]
            {
                "Price",
                "149.99"
            });
#line 14
            testRunner.And("Level options of", ((string) (null)), table2, "And ");
#line hidden
            var table3 = new TechTalk.SpecFlow.Table(new string[]
            {
                "field",
                "value"
            });
            table3.AddRow(new string[]
            {
                "MembershipFormat",
                "Membership Card Format"
            });
            table3.AddRow(new string[]
            {
                "other",
                ""
            });
#line 18
            testRunner.And("Benefits options of", ((string) (null)), table3, "And ");
#line hidden
            var table4 = new TechTalk.SpecFlow.Table(new string[]
            {
                "field",
                "value"
            });
            table4.AddRow(new string[]
            {
                "Installments",
                "Yes"
            });
            table4.AddRow(new string[]
            {
                "other",
                ""
            });
#line 22
            testRunner.And("Dues options of", ((string) (null)), table4, "And ");
#line hidden
            var table5 = new TechTalk.SpecFlow.Table(new string[]
            {
                "field",
                "value"
            });
            table5.AddRow(new string[]
            {
                "Term",
                "Varies with the membership start date (based on a rolling year)"
            });
            table5.AddRow(new string[]
            {
                "other",
                ""
            });
#line 26
            testRunner.And("Renewal options of", ((string) (null)), table5, "And ");
#line 30
            testRunner.And("the Review is Saved", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 31
            testRunner.Then("\"Test Program\" should be listed in Membership Programs", ((string) (null)),
                ((TechTalk.SpecFlow.Table) (null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}

#pragma warning restore

#endregion